version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USER: arn:aws:secretsmanager:ap-south-1:717279697458:secret:dev/docker/creds-PIQymI:DOCKERHUB_USER 
    DOCKERHUB_TOKEN: arn:aws:secretsmanager:ap-south-1:717279697458:secret:dev/docker/creds-PIQymI:DOCKERHUB_TOKEN

phases:
  install:
    runtime-versions:
      golang: 1.20
    # commands:
    #   - echo "Installing dependencies..."
    #   - curl -LO https://github.com/docker/setup-qemu-action/releases/download/v2.0.0/setup-qemu-action.sh
    #   - chmod +x setup-qemu-action.sh
    #   - ./setup-qemu-action.sh
    #   - curl -LO https://github.com/docker/setup-buildx-action/releases/download/v2.0.0/setup-buildx-action.sh
    #   - chmod +x setup-buildx-action.sh
    #   - ./setup-buildx-action.sh

  pre_build:
    commands:
      - echo "DockerHub authentication..."
      - echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USER --password-stdin
      - echo "AWS ECR Public authentication..."
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      - echo "Running CI script..."
      - src/catalog/scripts/ci.sh
      - echo "Enabling Docker Buildx..."
      - docker buildx create --use
      - docker buildx ls

  build:
    commands:
      - echo "Building container image..."
      - scripts/build-image.sh -s catalog -t ci

artifacts:
  files:
    - '**/*'